### ISSUE TITLE
Encounter search returns Bad request from Reference Server

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#101]
Is the 400 response because there is no data in the reference server, or is there something else wrong here?

![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/a23ac9ef-419f-48d2-a330-d0ea77b207c0)

**Comment by projkov** [comment]
@heathfrankel Hello Heath

In this particular case, the problem is related to the unknown search parameter "discharge-disposition" for the HAPI server. You can see this by clicking the details button, which will open a modal window. Scroll down if needed, and you will see the response data.

```json
{
  "resourceType": "OperationOutcome",
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "HAPI-0323: Unknown search parameter &quot;discharge-disposition&quot; for resource type &quot;Encounter&quot;. Valid search parameters for this search are: [account, appointment, based-on, class, date, diagnosis, episode-of-care, identifier, length, location, location-period, part-of, participant, participant-type, patient, practitioner, reason-code, reason-reference, resource-placeholder, service-provider, special-arrangement, status, subject, type]"
    }
  ]
}
```

---
In general, if we have some code for the response in the test, it means that all the data for the test has been retrieved.

**Comment by heathfrankel** [comment]
Behaving as expected.
Discharge disposition is a custom parameter and hence HAPI does not know about and returns 400.

Proposal to remove copnformance requirement of discarge-displosition

However, as AU_CBASE defines this search parameter, the Sparked Server should be configured to support this search parameter.
New card please
