### ISSUE TITLE
Encounter search MAY requirement tests

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core-inferno#102]
Encounter search by patient + discharge-disposition is a MAY requirement, yet still shows as Option as it does for SHOULD requirements.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/19570702/a23ac9ef-419f-48d2-a330-d0ea77b207c0)

Suggest that there needs to be a differentiator between SHOULD and MAY and one is more a recommendation than optional.

**Comment by projkov** [comment]
@heathfrankel hello Heath

I think, in case of the inferno tests "optional" status is more about "can be missing, failed, etc without affecting the result" than sense according to the FHIR.

If we need to show to the user that this "optional" test is "optional" because its MAY or SHOULD, then we can add this information to the "About" tab for each test of we can add it to the title of the test. What do you think?

**Comment by heathfrankel** [comment]
patient + discharge-disposition is actually SHOULD requirement, discharge-disposition is MAY.
The issue is that we can not distinguish between them.
There is no easy way to change the display of Optional to Recommended for SHOULD.
Suggested change is to prefix the Test title with (SHOULD) and (MAY) to display after Optional.
E.g. 
> 1.15.11 Optional (SHOULD) Server returns valid results for Encounter search by patient + discharge-disposition

**Comment by projkov** [comment]
Hello @heathfrankel ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/
