### ISSUE TITLE
Implement validation of FHIR resources using the Inferno test

### ISSUE THREAD

**Issue by projkov** [hl7au/au-fhir-core-inferno#150]
Currently, Inferno is used as the official validator wrapper, but it's broken right now because the configuration is not finished. We have decided to use the Inferno test for resource validation. This approach has many advantages:

1. Prefilled link to the terminology server.
2. Preselected and already downloaded Implementation Guide (IG) for the validator with a specific version.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

Now users can use the Inferno test as a validator feature. This test group is optional, so it doesn't influence the final result of all tests.

Users just need to paste the resource into the input and run the test. As a result, users will get a report in the messages tab. Additionally, I have added supporting information about the resource being validated, the IG version, and the profile used for the validation.

You can check the report.
https://inferno.hl7.org.au/au_core_v040_preview/lbhR4GJCQNm#au_core_v040_preview/report

Please try it out. The test group number is 1.23 Custom validation. Thanks!

**Comment by StephThaoOng** [comment]
> paste the resource into the input and run the test. As a result, users will get a report in the messages tab. Additionally, I have added supporting information about the resource being validated, the IG version, and the profile used for the validation.
> 
> You can check the report.

@projkov Thanks Pavel!
I tried it and it works. 
The modal field _FHIR resource in JSON format (custom validation)_ to paste in the resource is small though. Can this be larger?
Also when the user tries to upload a resource in the JSON view, it inadvertently removes the other input parameters and results in an error as shown below. 
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/189fa46d-5235-4664-830b-0530ab23cf1d)

The rendering of the resource in JSON format doesn't seem user friendly. Particularly when the instructions/information say "The intended use of this view is to provide a template for users to copy/paste in order to avoid filling out individual fields every time." 
Happy to wait until we get more feedback after next week before we look to make any improvement, if necessary :)

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

I made a small update: use text input, not a string. It makes it more readable.

Confirm that we don't need to do anything with this issue and that we are waiting for feedback after the test event.

If this is correct, then please close the issue. Thanks!
