### ISSUE TITLE
Please provide option for using READ by Id on Patient if Search by _id is not available

### ISSUE THREAD

**Issue by nielmdrec** [hl7au/au-fhir-core-inferno#163]
When running the inferno test kit, our product fails on Patient early because we have not implemented
Patient SEARCH by _id since we already have READ Patient by id.

This then blocks us from testing the rest of Patient.

It would be good to have the option of continuing the Patient test suite with READ rather than SEARCH.

**Comment by projkov** [comment]
@nielmdrec Hello!

Thank you for reporting this issue. I'm happy to announce that this feature is available in The AU Core Test Kit v0.0.11 (https://github.com/hl7au/au-fhir-core-inferno/releases/tag/v0.0.11).

Now, when you run the suite, you can use a setting called "Use read instead of search? (required)." By default, it's set to false. If you set it to true, the first search test by _id will fail, but the test suite will try to use read instead of search. The data will be available in the subsequent tests.

Please try the new functionality. I hope it will be helpful in your case! I look forward to your feedback. Have a good day!

**Comment by nielmdrec** [comment]
Thank you very much, Pavel.

**Comment by projkov** [comment]
Hello @nielmdrec 

I'm happy to announce that the ability to use the READ interaction for the first search by Patient ID is now available automatically, without any action required from the user's side.

When you run the AU Core Test Kit, it will first attempt to search for the patient by _id. If the search by _id is unavailable, it will automatically retrieve the data using the READ interaction.

This feature is available starting from version 0.0.12. Feel free to try it out. I would be happy to receive any feedback from you.

https://inferno.hl7.org.au/
