### ISSUE TITLE
Practitioner search parameter _id is SHOULD not SHALL

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#196]
In the AU Core Responder CapabilityStatement the Practitioner resource search parameter _id is SHOULD not SHALL. This should be an optional test.

The structured content of the Responder CapabilityStatement has SHOULD, but the narrative text has a copy paste error of SHALL and will be corrected by https://jira.hl7.org/browse/FHIR-46777.

**Comment by projkov** [comment]
@dt-r Hello Danielle

https://hl7.org.au/fhir/core/1.0.0-ballot/CapabilityStatement-au-core-responder.json
According to this CapabilityStatement responder, the _id search parameter for the Practitioner resource is SHALL.

When it is fixed in the IG, it will be resolved automatically in the test suite.

**Comment by dt-r** [comment]
Change is applied in current build of AU Core.

**Comment by StephThaoOng** [comment]
8/11 HL7 AU FHIR Tooling Community call: reinstate Inferno AU Core ci-build test suite to check if the generator has updated the auto generated test for [practitioner_id_search_test.rb](https://github.com/hl7au/au-fhir-core-inferno/blob/master/lib/au_core_test_kit/generated/v1.0.0-ballot/practitioner/practitioner_id_search_test.rb) correctly. If so, issue can be closed

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

In the CI build the search by _id has SHOULD expectation. The issue can be closed. 

I will close it. Thanks!
