### ISSUE TITLE
Provide guidance om how inferno validator works

### ISSUE THREAD

**Issue by ir4y** [hl7au/au-fhir-core-inferno#2]
We need a text narrative that describes how the validator could be used.
Also, we need to preload the IG package into the validator.

Now validator sends a request to localhost that is incorrect, it should use the base URL of the deployed server:
<img width="1280" alt="Screenshot 2024-03-06 at 15 45 30" src="https://github.com/hl7au/au-fhir-core-inferno/assets/1488983/a9ea795b-1398-43bc-ab28-0df04efba71d">

**Comment by projkov** [comment]
It looks like we don't need to preload IGs into the validator because it already downloads all IGs from "https://packages2.fhir.org/packages/catalog". In this case, AU core profiles are available from "https://packages2.fhir.org/packages/catalog?op=find&name=hl7.fhir.au.core&pkgcanonical=&canonical=&fhirversion=".

**Comment by projkov** [comment]
It's a guide for users

https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/validator_instructions.md
