### ISSUE TITLE
Tests not marked as Optional but need to be

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#57]
The following need to be considered Optional tests as AU Core lists them as SHOULD. It looks like the equivalent inferno tests do not mark them as Optional and need to be fixed:
* patient + category + status in all Observation profiles e.g. 1.5.09 Server returns valid results for Observation search by patient + category + status
* 1.17.10 Server returns valid results for MedicationRequest search by patient + intent + authoredon

Checked version AU Core v0.3.0-ballot

**Comment by projkov** [comment]
This issue is related to the problem with inconsistent state of the narrative and JSON files. In the current situation in CapabilityStatement  server JSON file combo search parameter patient+category+status is SHALL, not SHOULD.

**Comment by projkov** [comment]
Fix for the Observation resource is available in version 0.4.0-ci-build because it was corrected in the IG. https://jira.hl7.org/browse/FHIR-45390

For the MedicationRequest, I created a ticket in Jira (https://jira.hl7.org/browse/FHIR-46167) and decided to add a temporary fix in the code

This week's fix will be available in version 0.0.6 of the test kit.

**Comment by projkov** [comment]
Hello @dt-r ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/
