### ISSUE TITLE
Add missing _revinclude Provenance test to Practitioner tests

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core-inferno#59]
Missing the following test for Practitioner: Server returns Provenance resources from Practitioner search by _id + revInclude:Provenance:target

Please add.

Checked version AU Core v0.3.0-ballot

**Comment by projkov** [comment]
@dt-r Hello Danielle

This problem exists because there's a bug in the CapabilityStatement Server resource.

How to reproduce the bug:

Use the FHIRPath expression on the CapabilityStatement server resource.
Expression:
`CapabilityStatement.rest.resource.where(searchRevInclude.exists()).type`

As a result, you will get a list of resource types where the `searchRevInclude` attribute exists:

- AllergyIntolerance
- Condition
- Encounter
- Immunization
- Location
- MedicationRequest
- MedicationStatement
- Observation
- Organization
- Patient
- PractitionerRole
- Procedure

As you can see, the Practitioner resource is missing from this list.

I can raise a ticket, but it looks like my personal account in JIRA is restricted or something similar.

**Comment by dt-r** [comment]
This ticket is no longer relevant. AU Core Provenance and support for _revinclude have been removed from AU Core R1.
