### ISSUE TITLE
client request(s) and server response(s) are not displayed for failed tests.

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#71]
Currently, client request(s) and server response(s) are not displayed for any failed tests.
Example: 
![InfernoIssue01](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/481f0de0-5bc4-413d-9975-790b68f71198)

Request for a fix to display request(s) and response(s) for all tests, where applicable, even for failed tests.

**Comment by projkov** [comment]
Hello @StephThaoOng 

There is no output of request and response because, in this particular case, the request was not sent. This test is not running because there is no data for the search parameters (patient or date) for the current search test.

This information is automatically retrieved from the previous responses. It may be missing the date for the Procedure resources that were in the previous responses.

**Comment by StephThaoOng** [comment]
Thanks @projkov.
Perhaps the below screenshot is a better example of the issue where requests and responses are not displayed for a failed test.
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/eac2a392-3d40-410d-8be3-e3135d8c9693)
This test does not appear to have dependencies on any previous tests in the test suite.
Which raises another enhancement request - dependencies between tests to be documented/made known to users. I'll raise this separately. Thanks!

**Comment by StephThaoOng** [comment]
Thanks @projkov. 

I can see that the narrative under section "Testing Methodology > Searching > Search Parameters" is intended to call out the dependencies between tests so that it is made known to users. 

Can we consider uplifting these narratives so that they are specific to each test suite/sequence?
i.e. the current narrative in the Procedure Tests reads "...For example, the identifier search in the patient sequence is performed by looking for an existing Patient.identifier from any of the resources returned in the _id search. If a value cannot be found this way, the search is skipped." which doesn't seem applicable to the Procedure Tests.

**Comment by projkov** [comment]
@StephThaoOng Hello Steph

I made a list of errors that can be raised in tests. Could you please review them and maybe highlight unclear error texts for users?
https://github.com/hl7au/au-fhir-core-inferno/blob/master/docs/errors_list.md

**Comment by StephThaoOng** [comment]
Thanks @projkov 
Looks good. What do you think about minor tweaks suggestued below:

| Error|
|--------|
| Could not find values for all search params ~~identifier~~ identified|
| There are no resources of the type ~~Patient~~ [_resource type_] from previous tests, and you didn't provide IDs to search. |
| No ~~Patient~~ [_resource type_] resources conforming to the ~~http://hl7.org.au/fhir/core/StructureDefinition/au-core-patient~~ [_profile url_] profile were returned|
| Cell |

**Comment by projkov** [comment]
@StephThaoOng Hello Steph
Thanks, I used your suggested text in the document. Except this one:

```text
Could not find values for all search params identified
```

Because this error means that the identifier was not found. It can be any element name like date, gender, etc. Or it can be a list of parameters, like: "Could not find values for all search params date, gender"
