### ISSUE TITLE
Testing mandatory elements and required bindings

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core-inferno#81]
For testing the presence of mandatory elements and that elements with required bindings contain appropriate values, are the Inferno tests checking that systems "demonstrate at least one valid example in order to pass this test"? Should the systems demonstrate that ALL test resources are valid/pass the tests?
Example of profile validation test from the AllergyIntolerance test suite:
![image](https://github.com/hl7au/au-fhir-core-inferno/assets/36804832/2c0bb27b-2743-4774-8f0a-2344227069b9)

**Comment by projkov** [comment]
@StephThaoOng hello Steph. 

I think it may be an incorrect narrative of the test, because according to the source code, **it is not true**.
_If at least one resource from the first search is invalid, the tests will fail._

The first search is the initial search of the test group. In general, it is the first test. In the case of the AllergyIntolerance resource tests, the first search is a search by the "patient" search parameter.

**Comment by projkov** [comment]
Hello @StephThaoOng  ,

I'm pleased to announce that the changes related to this ticket are now available in version 0.0.6, which has already been deployed to the server.

Please re-test the changes. If everything is okay, you may close this ticket. If you encounter any issues or do not observe the changes related to this ticket, please provide details here.

Thank you.

https://inferno.hl7.org.au/
